### ISSUE TITLE
Incorporar cambios a master

### ISSUE THREAD

**Issue by ramirezfranciscof** [nanolebrero/lio#31]
Cuando quiero incorporar a master cambios de una rama 'branch' que esta actualizada en github, hay que hacer lo siguiente:

git checkout master
git pull --squash origin branch
git commit
git push -u origin master

¿Cómo puedo hacer lo mismo pero ahora con 'branch' una rama local mía que no esta sincronizada con github?

(esta forma para mergear me la tiraron en otro issue (el de sacar la matriz S), pero me pareció que podía ser mejor tener un thread saparado para esta consulta y otras relacionados con el mergeo a master)

**Comment by ramirezfranciscof** [comment]
Che, ¿puede ser que cuando hago merge/pull squash no me lo reconozca como merge posta? Por ejemplo: estoy en master, hago una rama mod1, hago los cambios y comiteo, vuelvo a master y hago merge --squash y después comiteo; cuando hago git branch -d mod1 me dice "error: The branch 'mod1' is not fully merged."

**Comment by manuelF** [comment]
Cuando squasheas, generas un nuevo commit C con todos los cambios. Ese
commit nunca existió, porque en la otra branch son N commits separados K1
K2 ... KN. Es como si hubieras tenido una iluminacion y hubieras hecho
muchas modificaciones de una al codigo. Ese C nuevo nunca existió en la
otra branch, entonces cuando queres borrarla te va a decir que no mergeaste
los K1... KN commits al master. Lo cual es cierto, solo hiciste un cambio
que casualmente, es el squash de K1 a KN, pero git no lo sabe.

En resumen, si mergeaste correctamente la branch a master y ya queres
deshacerte de la historia de tu branch, borrala con -D, que fuerza el
delete.

**Comment by ramirezfranciscof** [comment]
Ahh, ok, gracias. Follow up question: En vista de eso ¿Cuándo conviene hacer squash commits y cuando conviene commitear directo? (supongo que el default debería ser comitear directo ya que es la forma "más compatible" con el trackeo que hace git; "salvo en los casos en los que ..." fill in the blanks)

**Comment by manuelF** [comment]
Una branch separada representa una funcionanlidad que estas agregando. Si no podes hacerla en un solo commit (por ejemplo, una reestructuracion muy grande), entonces deberias hacerla en muchos y despues mergearla como un solo commit squasheado, para poder identificar que fue ese cambio que introduzco ese codigo. El problema ahi es que si es un commit demasiado grande que toca muchas cosas, puede ser dificil de revisar por biseccion la rama de si llegase a haber un problema que se detectase mas adelante. 

Asi que en mi opinion, conviene que un commit sea lo mas chico posible y que squashees cuando no lo puedas hacer en un solo commit, separado por funcionalidad (1 commit == 1 funcionalidad nueva).

**Comment by ramirezfranciscof** [comment]
Mmmm ¿o sea que la idea es que SIEMPRE hagamos squash SALVO que lo mergeado tenga un solo commit (correspondiente a una funcionalidad)? Yo por lo menos commiteo con relativa frecuencia cuando trabajo en mis ramas, como por ejemplo cuando arreglo un bug en una determinada parte del código (aunque queden bugs en otras). A veces incluso por cuestiones prácticas (tengo que ver una cosa en otra rama y no me deja cambiar de ramas si no tengo los cambios commiteados).

**Comment by ramirezfranciscof** [comment]
Exchange dead end. If any desire to continue exchange of similar ideas related to this, please re-frame question and open new issue.
