### ISSUE TITLE
Mergear CuBLAS

### ISSUE THREAD

**Issue by manuelF** [nanolebrero/lio#4]
Subir las ultimas versiones de TD DFT que usan CUBLAS.

**Comment by fedepedron** [comment]
¿Esto está ya resuelto? ¿Puede cerrarse el issue?

**Comment by segmentat10nfault** [comment]
si, cerrado nomas

**Comment by ramirezfranciscof** [comment]
@segmentat10nfault para cerrarlo tenes que tocar el boton "Close and comment".
