### ISSUE TITLE
Instructions on how to compile Amber with LIO?

### ISSUE THREAD

**Issue by manuelF** [nanolebrero/lio#41]
Creo que estaria faltando en el repositorio algun escrito/Makefile/simil que explique los pasos necesarios para conectarlos, así lo agregamos al README también.

---

EDIT: I think we should add some instructions to explain how to compile amber with lio. We should add it to the README as well.

**Comment by fedepedron** [comment]
¿Esto se arregló ya? Por las dudas, estaría bueno poner instrucciones similares para gromacs.

**Comment by ramirezfranciscof** [comment]
Yo [acá en la home de la wiki](https://github.com/nanolebrero/lio/wiki) copypastee los comandos que use la ultima vez para compliar mis cosas como para tenerlo de referencia. Si alguien puede completarlo mejor; y vos podes agregar otro apartado para GROMACS. Después se puede incluir versiones con más detalle en el manual.

**Comment by fedepedron** [comment]
The thing with Gromacs is that is not yet official on the other side. We can always make our own Gromacs-fork though.

**Comment by ramirezfranciscof** [comment]
What do you mean? That you have to make modifications on Gromacs source code to compile it with lio? I think that the solution for that would be to include with our distribution the files you need to overwrite in Gromacs and explain where to copy those. At least till Gromcs accepts the truth of LIO.

**Comment by fedepedron** [comment]
Readme updated in rc.
