### ISSUE TITLE
Compilation Changes

### ISSUE THREAD

**Issue by ramirezfranciscof** [nanolebrero/lio#43]
Acabo de mergear a master unos cambios al proceso de make para que sea un poco mas versatil para organizar los archivos internamente y de más sencilla modificación. No es perfecto, pero la idea es que sea temporario; eventualmente habría que hacer uno mejor que compile todo el programa (g2g, liosolo). A mí me esta funcionando; pero avisenme si hay algun problema o otras cosas que no gusten.

Pequeño detalle: hay algunas cosas (el keyword "private") que requieren make 3.82 o más nuevo y yo por lo menos tuve que instalarlo y para eso seguí las instrucciones de acá: http://askubuntu.com/questions/509012/make-3-82-on-ubuntu-12-04.

**Comment by ramirezfranciscof** [comment]
Luego de charlarlo con @jpdarago decidimos cambiar esto para evitar que haya problemas con la compilación para versiones viejas de make. Espero que no joda que deje este issue abierto porque estaría bueno en algun momento volver a ajustar esto, ya que la implementación actual tiene aparejadas algunas otras consecuencias no super felices que le restan versatilidad (que es cierto que en estos momentos no necesita) al proceso de compilación.

**Comment by ramirezfranciscof** [comment]
OK @manuelF , Now i am starting to have compilation annoyances myself. Perhaps this might help find the error since it seems like a relatively simple case to analize:

make clean
make
make

First make compiles all objects, second make does nothing (Nothing to be done). Now I do:

touch mathsubs/mathsubs.f
make
make
make

First make compiles mathsubs/mathsubs.f (twice), SCF.f and SCFop.f. It compiles twice mathsubs, guess that it has to do with the .o and .mod both being dependencies, but if that was all there would be no problem. The thing is, second make does compile something: mathsubs/mathsubs.f again and only once. Then the third make compiles mathsubs/mathsubs.f once, SCF.f and SCFop.f.

From then on, successive makes repeat the pattern of the second and third make, alternating. Eliminating the dependency on the .mod files seems to eradicate this behavior, but I think it would be better to understand the underling reason and find the proper way to deal with it (or at least verify that the correct thing to do in fortran is to drop the dependency of the .mod files).

@manuelF  you can check if commenting the .mod dependencies fixes the make -f  problem too to check if that also has to do with this.

**Comment by manuelF** [comment]
@ramirezfranciscof Thanks. Fixing the mod dependencies has eliminated this issue.  As far as I can tell, it is not a problem anymore. I think it can be pushed to master.

If you'd like to inspect it more, this link I think has some information on this .o .mod issue 
http://lagrange.mechse.illinois.edu/f90_mod_deps/ but I am not too sure on what is the best possible solution to this. The only thing that comes to my mind would be trying the option "How to express to make the fact that compiling produces several files simultaneously" , as it is similar to what we were trying to accomplish by adding the .mod explicit dependency (provided the FORTRAN source files do not generate more modules than one per .f file) . 

How does that look ?

**Comment by ramirezfranciscof** [comment]
@manuelF  Great finding that link. I agree that "2. How to express..." is probably the best way to go. We should only need to eliminate lines 79 and 80 in makefile and add `$(obj_path)/%.mod` as a target in line 76, right? were you able to try this and check if it returned any mistakes?

**Comment by ramirezfranciscof** [comment]
I implemented the solution. It apparently compiles with no problem and the test runs worked.

**Comment by ramirezfranciscof** [comment]
I think I have isolated the problem and found a pretty decent solution.

Apparently the fortran compiler does not overwrite .mod files if they have no changes (for example, if I only "touched" the .f file, like in my example), even though they DO overwrite the .o file. If make notices that the .f has a last modified date that is more recent than the .mod file, it will then recompile, but will only overwrite the .o file, and the .mod file will always have a date that is less recent than the .f (and this will always cause make to recompile the module).

I think a possible solution for this behavior is to have make "touch" the .mod files after compiling them, so that the time is updated. I have tried this and seems to fix the behavior I exposed here. I am updating the makefile to work like this (also, I am making the .o files that use modules depend on just the module.mod file instead of both those and the module.o files, since this seems to be the strict dependency (you need the module.mod to compile an object that uses the module; the module.o is only needed for linking).

(Source: http://lists.gnu.org/archive/html/help-make/2011-01/msg00103.html)

**Comment by ramirezfranciscof** [comment]
Previous comment should have closed this issue.
