### ISSUE TITLE
Problems with rc

### ISSUE THREAD

**Issue by ramirezfranciscof** [nanolebrero/lio#47]
(1) The makefile for the cuda part is using a LIOPATH that points to the lio folder, but if I am not mistaken, the LIOPATH that Amber needs has to point towards lioamber folder (where the library is). I think this part requires a revision of it's make process.

(2) The test I was running is returning different values of energy each time I run it. Moreover (and easier to check without me uploading the input I am using), when I try to run the official tests, I get the following error code:

    Running 0_aguaCPU...
	Recompiling...
	Options: cpu=1 openmp=0 time=1 non_optimize=1
	Recompiling Done
	Running...

	Result = Summary(iterations=60.0, converged=True, total_time=1380047.0, avg_time=23000.783333333333, scf_energy=-55.71249688915623)
	Expected = Summary(iterations=14.0, converged=True, total_time=442044.0, avg_time=31574.571428571428, scf_energy=-76.0668404034146)

	SCF Diff: 20.354344
	Time increase: 212.196750 %
	Failed because not acceptable result: invalid numerical result

    Running 0_aguaGPU...
	Recompiling...
	Options: cuda=1 sm20=1 time=1
	Recompiling Done
	Running...
    Fortran runtime error: dimension of array B incorrect in MATMUL intrinsic
	Failed to run with errcode 2
    1 tests fallaron...

**Comment by chopkins906** [comment]
(1) I'm assuming you're talking about the "LIOHOME" variable? (correct me if I'm wrong here)

Amber expects LIOHOME to point to the top level of the lio install, which I think agrees with how lioamber/make.inc and lioamber/drive.f use it (I think those are the only two places lio itself actually uses that variable currently).  I pulled the relevant line from the Amber configure script:

liolibs="-L/usr/lib -L/usr/lib64 -L$LIOHOME/g2g/ -lg2g -L$LIOHOME/lioamber -llio-g2g"

(2) I was able to run the CPU water test manually by itself OK; it looks like the compile options are outdated though for the automated test.  There needs to be a "cuda=0" in there somewhere I think.

I am having a problem with the GPU water test though (interestingly the bigger tests - caffeine, hemo, caroteno - run fine).  It seems that in a recent commit, that test was changed to run TD (timedep=1 - not sure if that was intentional).  If I run with timedep=0, I do get an error: "NAN en fock2"

**Comment by ramirezfranciscof** [comment]
(1) Is this so? Because I was able to make and run amber and my LIOHOME always pointed to the lioamber subdir. Perhaps since I have g2g and lioamber explicitly in my LD_LIBRARY_PATH it used it from there directly? (this part of my bashrc has alway been "copied" from other sources)

(2) Should I have problems when compiling with a simple "make"? Because when I do that and run my test, I get varying coulomb and one electron energy contributions.

**Comment by chopkins906** [comment]
(1) Yes, I think setting LD_LIBRARY_PATH like that is fixing up the "wrong" LIOHOME and letting you link Amber/lio.  A "correct" LIOHOME (set to the root lio directory) is necessary if people don't have LD_LIBRARY_PATH set up ahead of time, and it will also be necessary for using the "basis set keyword" feature (and maybe also to compile the new cublas stuff?).

(2) doing just a "make" should be fine.

Couple of questions: what is your GPU setup you're testing with: how many GPUs and what model(s)?
More importantly, how much of a variation are you seeing?

I have noticed that when running with multiple GPUs, there can be some very small variation in the energy from run to run, but in my tests it's always less than the convergence threshold (for instance, on the order of 10^-7 for the caffeine test).  Do you see a much bigger difference than that from run to run?

In my case, if I force it to run with just one GPU (by setting e.g. CUDA_VISIBLE_DEVICE='0') the variation disappears and I get the exact same answer each run; I've been assuming it has something to do with variability in the ordering of threads in the multi-GPU XC code changing the order of operations slightly.

**Comment by ramirezfranciscof** [comment]
(now all that is left is 2 so I'll stop indexing)

I have only one GPU gtx680, and variation in my test goes from:
 SCF ENRGY=  -75.738564392959589     
 SCF ENRGY=  -115.24268325844430     
 SCF ENRGY=  -103.01515874854856     
 SCF ENRGY=  -75.619447547412079     
 SCF ENRGY=  -114.26787553158637     
 SCF ENRGY=  -107.08726725205281     

So you'll see they're quite grotesque. Nuclear energy remains stable, but one electron and specially coulomb vary wildly.

**Comment by chopkins906** [comment]
Yep, there seems to be a problem in the GPU code during that test, at the very least in the nuclear attraction (one electron) calculation - I'm assuming it only shows up for very small test cases, as I can run the other tests fine.  I'm looking into it now.

**Comment by ramirezfranciscof** [comment]
Ok, thank you chad! Let me know if I can do something to help.

**Comment by chopkins906** [comment]
OK, the problem is fixed now in the rc branch - the aguaGPU test should pass.

**Comment by ramirezfranciscof** [comment]
Yes, thanks, the test seems to be running alright and my test run is also working.
