### ISSUE TITLE
Compilation problem with gfortran

### ISSUE THREAD

**Issue by ramirezfranciscof** [nanolebrero/lio#49]
I have just uploaded some changes into rc. Compilation seems to work fine with ifort=1, but regular make (with gfortran as default) is giving me this error:

> *** glibc detected *** /lio//liosolo/liosolo: malloc(): memory corruption: 0x000000000229e3a0 ***

The error seems to originate from the call to int2 in line 534 of SCF.f. I have not modified this routine, so I don't quite know what is causing it. I will be trying to find more about it tomorrow, but I'm just putting this here in case anybody thinks of any reason this may be happening. Also, I am not sure that it happens with any system (I think one of my test systems fails and the other seems to run normally, don't know if perhaps there is an if that is skipping this in the second case).

Please let me know if there is any other inconvenience related to this.

**Comment by chopkins906** [comment]
A while ago, I did have a sporadic issue with a lapack call in int2 when doing a gnu build and compiling g2g with dbg=1, some kind of undefined behavior going on.  It disappeared using ifort=1 or dbg=0.  Are you compiling g2g with dbg=1, by chance?

I never really figured out what was going on, and I haven't seen it happen for a while though.

**Comment by ramirezfranciscof** [comment]
If it is the default, then yes. I am doing only "make", no keywords. Now I am not sure if it is in int2, because on a first examination I could swear that the error manifested when I get to that part, but right now it seems to be more strange: this may have a name that i don't know of, but the way I would describe it is that the error doesn't cause an immediate stop, but when the program does eventually stop (accumulation maybe?) it shows the error message. I know this because I can write to the screen in many places and still get the error.

I will now try to learn how to use valgrind to debug this (that is apparently very useful to find bad memory usage, which seems to be causing this).

**Comment by ramirezfranciscof** [comment]
Ignore the close-open, missclicked.

Is there a way to add `-g` and `-O0` to compiling options when making from the main folder? @chopkins906 @nanolebrero

**Comment by nanolebrero** [comment]
With non_optimize=1 compile with -O0.
I think that -g is always on.


2015-08-14 9:33 GMT-03:00 ramirezfranciscof <notifications@github.com>:

**Comment by ramirezfranciscof** [comment]
Found my bug, explanation in the commit message. In the end it was not a problem in int2, so it probably isn't related with what @chopkins906 just reported: if you find that the problem manifests again, please do let us know. Ending issue.
