### ISSUE TITLE
compile error for GTX TITAN

### ISSUE THREAD

**Issue by c00jsw00** [nanolebrero/lio#50]
could you fix the bug ?

NVCC == 6.5
linux   == centos 6.3
error:
ptxas /tmp/tmpxft_0000549c_00000000-5_iteration.ptx, line 937582; error   : Call has wrong number of parameters
ptxas fatal   : Ptx assembly aborted due to errors
make[1]: *** [cuda/iteration.cu_o] Error 255
make[1]: Leaving directory `/home/c00jsw00/bin/lio/g2g'

**Comment by c00jsw00** [comment]
When using cuda 7.0, I have overcome the bug.

**Comment by ramirezfranciscof** [comment]
Odd, I am running under cuda 6 and didn't get any problems. This occurs while compiling? Which options did you complie with?

**Comment by chopkins906** [comment]
I've been helping @c00jsw00 get set up with lio, and I believe he doesn't have anymore problems.

He was setting up with Amber and making some code modifications, that possibly was the cause of the issue.

Looking at the error message, my other guess might be that this was a CUDA ptxas caching issue that popped up from compiling multiple branches of code.  I've been using 6.5 and I haven't had any issues myself.

Either way, I think this can be closed for now, unless someone can reproduce the problem.
