### ISSUE TITLE
remove SCF unnecessary variables

### ISSUE THREAD

**Issue by Nick-Chaos** [nanolebrero/lio#61]
SCF tiene demasiadas variables que no utiliza lo que parece traer problemas al compilar con -check bounds

**Comment by fedepedron** [comment]
Removed almost all outside-SCF output writing, such as Mulliken, restarts, orbital coefficients, etc. Only left cubegen there since it needs xnano. See SCF comments at the bottom for more information, and try not to kill me =D

**Comment by Nick-Chaos** [comment]
Working on that, made a pull request with phase 1 of this issue

**Comment by Nick-Chaos** [comment]
Terminado, solo falta romper RMM y sacar sus punteros, pero es parte de este issue.
