### ISSUE TITLE
Escritura de propiedades 

### ISSUE THREAD

**Issue by segmentat10nfault** [nanolebrero/lio#63]
Las propiedades como momento dipolar o mulliken se tienen que poder escribir cada paso de una dinamica nuclear y no sobreescribirse al paso siguiente que es lo que hace ahora. 
Una solucion trivial es que escriba todo en el output y poner una buena referencia para despues poder grepear a piacere..
Otra opción es usar en los open, status=old. Eso indica que estas abriendo algo viejo que ya tiene algo adentro para que no lo pise. Lo que no me fije como hacer es que escriba abajo de todo, tal vez lo hace por default. Despues lo miro..

**Comment by fedepedron** [comment]
Suggestion moved into issue #66.
