### ISSUE TITLE
Using internal /dat basis set files.

### ISSUE THREAD

**Issue by fedepedron** [nanolebrero/lio#68]
I think this would be an interesting upgrade for the upcoming release; however, I am not being able to use it either with Gromacs or even with Lio alone. Is there a working version of this? It does not seem to be easily fixed.

**Comment by Nick-Chaos** [comment]
it works on liosolo, version 6fc10484903acbaec4f41654f19d927a75578ea5 and many commits before

**Comment by fedepedron** [comment]
Weird, drive has not been changed since that commit... unless it works only with gpu; I'm trying cpu-only version and leads to what I believe is a memory overflow.

**Comment by Nick-Chaos** [comment]
Try with a version older than 338d2595f61804dcd3790488d87513d37b05bcaf, it could be some problem in any allocation in XC cpu subs.

**Comment by fedepedron** [comment]
I backtraced the error to a "nnat" deallocation. Apparently it may be overwritten or smth, but it is easily fixed by removing nnat localization from lio_finalize and SFC_gro/SFC_in

**Comment by fedepedron** [comment]
Well, the issue was that nnat was being allocated with an inappropriate dimension. Now internal basis work from liosolo, liogromacs and (PROBABLY) lioamber.
