### ISSUE TITLE
Dipole subroutines

### ISSUE THREAD

**Issue by fedepedron** [nanolebrero/lio#76]
I've been recently cleaning the dip.f (now dip.f90) subroutine, and found there is also a "dipmem" subroutine which is never called anywhere, and is almost a copypaste from the original "dip" subroutine. Is there any use for this?

**Comment by nanolebrero** [comment]
Es una version que guarda cosas en memoria para no recalcular, la hice en
algun momento para ahorrar tiempo pero no se gana gran cosa.
